name: "prp-preprocessor"
description: "A GitHub Action that replaces variables in files"
branding:
  icon: "edit"
  color: "orange"
inputs:
  rootDir:
    description: "Root directory"
    required: true
    default: "."
  extension:
    description: "Preprocess files with this pre-extension"
    required: true
    default: ".prp"
  commitMessage:
    description: "Commit message"
    required: true
    default: "chore: process {_amount_} PRP files"
  encoding:
    description: "Encoding of the files"
    required: true
    default: "utf8"
  ignoredVars:
    description: "Ignore these variables"
    required: false
    default: ""
  ignoredDirs:
    description: "Ignore these directories"
    required: false
    default: ""
  includeSubDirs:
    description: "Include subdirectories"
    required: false
    default: "true"

runs:
  using: "node20"
  main: "dist/index.js"
