name: "Preprocessor"
description: "Example GitHub Action written in TypeScript"
branding:
  icon: "book-open"
  color: "white"
inputs:
  rootDir:
    description: "Root directory"
    required: true
    default: "."
  extension:
    description: "Preprocess files with this pre-extension"
    required: true
    default: ".prp"
  encoding:
    description: "Encoding of the files"
    required: true
    default: "utf8"
  ignoredVars:
    description: "Ignore these variables"
    required: false
    default: ""
  ignoredDirs:
    description: "Ignore these directories"
    required: false
    default: ""
  includeSubDirs:
    description: "Include subdirectories"
    required: false
    default: "true"

runs:
  using: "node20"
  main: "dist/index.js"
